export const COLOR_PALETTE = [
  '#42A5F5',
  '#EF5350',
  '#0A84FF',
  '#30D158',
  '#FF9F0A',
  '#FFD60A',
  '#BF5AF2',
  '#5E5CE6',
  '#FF375F',
  '#64D2FF',
  '#AC8E68',
  '#8E8E93',
] as const;

export const ICON_CHOICES = [
  'task_alt',
  'school',
  'menu_book',
  'edit',
  'calculate',
  'science',
  'language',
  'computer',
  'piano',
  'music_note',
  'brush',
  'palette',
  'cleaning_services',
  'bed',
  'local_laundry_service',
  'checkroom',
  'wash',
  'shower',
  'clean_hands',
  'restaurant',
  'kitchen',
  'local_dining',
  'pets',
  'yard',
  'local_florist',
  'recycling',
  'delete',
  'shopping_cart',
  'backpack',
  'directions_run',
  'sports_soccer',
  'directions_bike',
  'pool',
  'fitness_center',
  'self_improvement',
  'bedtime',
  'alarm',
  'volunteer_activism',
  'favorite',
  'star',
  'euro',
  'savings',
  'icecream',
  'cake',
  'local_pizza',
  'local_drink',
  'emoji_food_beverage',
  'smart_display',
  'sports_esports',
  'movie',
  'headphones',
  'phone_iphone',
  'toys',
  'extension',
  'attractions',
  'park',
  'celebration',
  'card_giftcard',
  'redeem',
  'rocket_launch',
] as const;

export const METER_FIGURES = ['truck', 'boat', 'plane', 'helicopter', 'ball'] as const;

export const DEFAULT_METER_FIGURE = 'truck';

export const METER_FIGURE_LABELS = {
  truck: 'Машинка',
  boat: 'Кораблик',
  plane: 'Самолётик',
  helicopter: 'Вертолётик',
  ball: 'Мяч',
} as const;
